### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by 0xd10b01a** [connesc/megaproxy#1]
megaproxy.cpp: In function 'int main()':
megaproxy.cpp:79:2: error: reference to 'SynchronousRequestListener' is ambiguous
  SynchronousRequestListener listener;
  ^
megaproxy.cpp:13:7: note: candidates are: class SynchronousRequestListener
 class SynchronousRequestListener : public MegaRequestListener {
       ^
In file included from megaproxy.cpp:8:0:
/usr/local/include/megaapi.h:3503:7: note:                 class mega::SynchronousRequestListener
 class SynchronousRequestListener : public MegaRequestListener
       ^
megaproxy.cpp:80:53: error: 'listener' was not declared in this scope
  megaApi.login(username.c_str(), password.c_str(), &listener);
                                                     ^
Makefile:7: recipe for target 'megaproxy' failed

**Comment by connesc** [comment]
Hi!

You're right, it should be fixed now.
Let me know if it's OK for you :wink:

**Comment by 0xd10b01a** [comment]
I have a lot of "undefined reference to mega::MegaApi::*"

any ideas?
Thank you

**Comment by connesc** [comment]
Maybe you have an incompatible version of the mega.nz SDK, or maybe it has been compiled without libuv.
Check that your are using [v3.0.0](https://github.com/meganz/sdk/releases/tag/v3.0.0), and configure it to use libuv:
```
./configure CXXFLAGS=-DHAVE_LIBUV=1 LDFLAGS=-luv
```

If by chance you are using Arch Linux, you can check my AUR package: [mega-sdk](https://aur.archlinux.org/packages/mega-sdk/). Otherwise, you may still find some hints in [its sources](https://aur.archlinux.org/cgit/aur.git/tree/?h=mega-sdk) (libuv is enabled differently, but the result should be the same).

**Comment by 0xd10b01a** [comment]
I've 3.0.0, run configure, make, make install again on sdk folder, but some result :(

Crazy thing: I've copied megaproxy.cpp in the examples folder of the sdk, and modified the inculde.am file, ran make clean && make, and it compiled! lol

**Comment by connesc** [comment]
So it's probably because your linker does not find the correct version of libmega.so.
Check that an older version has not been left by a previous install.

Also, you can tell the linker where to search for libmega by prepending `-lmega` with `-L/where/to/search` in the Makefile.

**Comment by 0xd10b01a** [comment]
Thank you

**Comment by connesc** [comment]
I close the issue since this is not directly related to megaproxy. Feel free to post here again if you need further help :wink:
